spring:
  profiles:
    active:
    - runtime
    - oauth

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: info